
FROM golang:1.25rc2

ENV OUTPUT_FILE_NAME=app

WORKDIR /rss-tg-bot

COPY go.mod go.sum ./

RUN go mod download

COPY src/*.go ./

RUN CGO_ENABLED=1 GOOS=linux go build -ldflags="-w -s" -o $OUTPUT_FILE_NAME

CMD ["sh", "-c", "./$OUTPUT_FILE_NAME"]