name: Build and Push Docker Images

on:
  push:
    branches:
      - master

env:
  APP_PATH: /home/${{ secrets.PRODUCTION_SERVER_USERNAME }}/rss-tg-bot
jobs:
  build:
    runs-on: ubuntu-latest
    environment: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx (for advanced building features)
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/rss-tg-bot

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     push: ${{ github.event_name != 'pull_request' }}
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push with Docker Compose
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker compose -f compose.yaml build
          docker compose -f compose.yaml push

      - name: Create application directory
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PRODUCTION_SERVER_ADDRESS }}
          username: ${{ secrets.PRODUCTION_SERVER_USERNAME }}
          password: ${{ secrets.PRODUCTION_SERVER_PASSWORD }}
          port: ${{ secrets.PRODUCTION_SERVER_PORT }}
          script: |
            set -e
            mkdir -p ${{ env.APP_PATH }}

      - name: Upload compose.prod.yaml with SCP
        uses: appleboy/scp-action@v1
        with:
          username: ${{ secrets.PRODUCTION_SERVER_USERNAME }}
          password: ${{ secrets.PRODUCTION_SERVER_PASSWORD }}
          host: ${{ secrets.PRODUCTION_SERVER_ADDRESS }}
          port: ${{ secrets.PRODUCTION_SERVER_PORT }}
          source: "compose.prod.yaml"
          target: "${{ env.APP_PATH }}/"

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        with:
          host: ${{ secrets.PRODUCTION_SERVER_ADDRESS }}
          username: ${{ secrets.PRODUCTION_SERVER_USERNAME }}
          password: ${{ secrets.PRODUCTION_SERVER_PASSWORD }}
          port: ${{ secrets.PRODUCTION_SERVER_PORT }}
          envs: TELEGRAM_BOT_TOKEN,DOCKERHUB_USERNAME
          script: |
            set -e
            cd ${{ env.APP_PATH }}
            docker compose -f compose.prod.yaml pull
            docker compose -f compose.prod.yaml up -d
