name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx (for advanced building features)
      uses: docker/setup-buildx-action@v3

    # - name: Log in to Docker registry
    #   uses: docker/login-action@v2
    #   with:
    #     registry: ghcr.io        # or your relevant registry
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images with Docker Compose
      run: |
        docker-compose -f compose.yaml build
